# 平台绑定的账号
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-batch
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-batch
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-batch
subjects:
- kind: ServiceAccount
  name: kube-batch
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-batch
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tf-job-operator-kube-batch
subjects:
- kind: ServiceAccount
  name: tf-job-operator
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: kube-batch
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pytorch-operator-kube-batch
subjects:
- kind: ServiceAccount
  name: pytorch-operator
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: kube-batch
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpi-operator-kube-batch
subjects:
- kind: ServiceAccount
  name: mpi-operator
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: kube-batch
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mxnet-operator-kube-batch
subjects:
- kind: ServiceAccount
  name: mxnet-operator
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: kube-batch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.sigs.dev
spec:
  group: scheduling.sigs.dev
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minMember:
              format: int32
              type: integer
            queue:
              type: string
            priorityClassName:
              type: string
          type: object
        status:
          properties:
            succeeded:
              format: int32
              type: integer
            failed:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha2

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.sigs.dev
spec:
  group: scheduling.sigs.dev
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight:
              format: int32
              type: integer
          type: object
        status:
          properties:
            unknown:
              format: int32
              type: integer
            pending:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha2

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minMember:
              format: int32
              type: integer
            queue:
              type: string
            priorityClassName:
              type: string
          type: object
        status:
          properties:
            succeeded:
              format: int32
              type: integer
            failed:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1

---
# Source: kube-batch/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-batch
  namespace: kube-system
  labels:
    chart: "kube-batch-0.4.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-batch
  template:
    metadata:
      labels:
        app: kube-batch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubeflow
                    operator: In
                    values:
                      - 'true'
      serviceAccountName: kube-batch
      containers:
      - name: kube-batch
        image: "kubesigs/kube-batch:v0.5"
        args: ["--logtostderr", "--v", "3"]
        imagePullPolicy: IfNotPresent
        
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 200Mi

---
# Source: kube-batch/templates/default.yaml
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: Queue
metadata:
  name: default
  namespace: kube-system
spec:
  weight: 1
