# docker build -t ai.tencentmusic.com/tme-public/notebook:vscode-ubuntu-gpu-base -f Dockerfile-gpu-base .

FROM ai.tencentmusic.com/tme-public/notebook:vscode-ubuntu-gpu-theia

USER root
# 安装中文，和基础的apt工具包
RUN apt update && apt install -y --force-yes --no-install-recommends vim apt-transport-https gnupg2 ca-certificates-java rsync jq  wget git dnsutils iputils-ping net-tools curl mysql-client locales sysstat && apt clean

RUN curl -LO https://dl.k8s.io/release/v1.16.0/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/

RUN echo "alias ll='ls -alF'" >> /root/.bashrc && \
    echo "alias la='ls -A'" >> /root/.bashrc && \
    echo "alias vi='vim'" >> /root/.bashrc && \
    /bin/bash -c "source /root/.bashrc"

RUN apt install -y libsasl2-dev libpq-dev && rm -f /usr/bin/python && rm -f /usr/local/bin/pip && rm -f /usr/bin/pip && ln -s /usr/local/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip

# 安装python包
RUN pip3 install --upgrade pip  && pip install gsutil pysnooper kubernetes simplejson sqlalchemy pandas numpy requests flask pymysql ray && \
    rm -rf /tmp/* /var/tmp/* /root/.cache

RUN pip3 install -U pylint
RUN pip3 install polaris-python --index-url https://mirrors.cloud.tencent.com/pypi/simple/  --extra-index-url https://mirrors.tencent.com/repository/pypi/tencent_pypi/simple/

RUN echo "alias ll='ls -alF'" >> /root/.bashrc && echo "alias la='ls -A'" >> /root/.bashrc && echo "alias vi='vim'" >> /root/.bashrc &&  /bin/bash -c "source /root/.bashrc"

# 手动安装vscode插件  Chinese (Simplified)  GitLens vscode-icons      Bracket Pair Colorizer    Auto Close Tag    Python Indent
#COPY ca-certificates.crt /ca-certificates.crt
#RUN cat /ca-certificates.crt >> /etc/ssl/certs/ca-certificates.crt


