apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frameworks.frameworkcontroller.microsoft.com
spec:
  conversion:
    strategy: None
  group: frameworkcontroller.microsoft.com
  names:
    kind: Framework
    listKind: FrameworkList
    plural: frameworks
    singular: framework
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            properties:
              name:
                pattern: ^[a-z0-9]{1,63}$
                type: string
          spec:
            properties:
              executionType:
                enum:
                - Create
                - Start
                - Stop
              retryPolicy:
                properties:
                  maxRetryCount:
                    minimum: -2
                    type: integer
              taskRoles:
                items:
                  properties:
                    frameworkAttemptCompletionPolicy:
                      properties:
                        minFailedTaskCount:
                          minimum: -1
                          type: integer
                        minSucceededTaskCount:
                          minimum: -1
                          type: integer
                    name:
                      pattern: ^[a-z0-9]{1,63}$
                      type: string
                    taskNumber:
                      maximum: 10000
                      minimum: 0
                      type: integer
                type: array
    served: true
    storage: true
status:
  acceptedNames:
    kind: Framework
    listKind: FrameworkList
    plural: frameworks
    singular: framework
  conditions:
  - lastTransitionTime: "2021-05-06T07:02:14Z"
    message: '[spec.versions[0].schema.openAPIV3Schema.properties[metadata].type:
      Invalid value: "": must be object, spec.versions[0].schema.openAPIV3Schema.properties[metadata].type:
      Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[executionType].type:
      Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[retryPolicy].type:
      Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[taskRoles].items.properties[frameworkAttemptCompletionPolicy].type:
      Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[taskRoles].items.type:
      Required value: must not be empty for specified array items, spec.versions[0].schema.openAPIV3Schema.properties[spec].type:
      Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.type:
      Required value: must not be empty at the root]'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
  - lastTransitionTime: "2021-05-06T07:02:14Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-05-06T07:02:14Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
